{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata: 
  name: {{ $.Release.Name }}-rules
  namespace: {{ $.Values.prometheusRule.namespace }}
  labels:
    app: {{ $.Release.Name }}
    release: {{ $.Values.monitoring.release }}
spec:
  groups:
  - name: {{ $.Values.prometheusRule.groupName }}.rules
    rules: 
    - alert: {{ $.Values.prometheusRule.name }}
      expr: {{ $.Values.prometheusRule.expr }}
      for: {{ $.Values.prometheusRule.for }}
      labels:
        severity: {{ $.Values.prometheusRule.severity }}
      annotations:
        summary: {{ $.Values.prometheusRule.summary }}
        description: {{ $.Values.prometheusRule.description }}
{{- end }}