{{- if .Values.monitoring.enabled }}
{{- range .Values.monitoring.targets }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Release.Name }}-monitor-{{ .name }}
  namespace: {{ $.Values.monitoring.namespace }}
  labels:
    app: {{ $.Release.Name }}-{{ .name }}
    release: {{ $.Values.monitoring.release }}
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ .name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: {{ .port }}
      path: {{ .path }}
      interval: {{ .interval }}
---
{{- end }}
{{- end }}
