version: '3.8'

services:
  app:
    image: ${APP_SERVICE_IMAGE}:${APP_SERVICE_VERSION}
    ports:
      - "${APP_SERVICE_PORT}:${CONTAINER_PORT}"
    environment:
      - MODEL_SERVICE_HOST= ${MODEL_SERVICE_HOST}
      - MODEL_SERVICE_PORT = ${MODEL_SERVICE_PORT}
      - APP_VERSION=${APP_SERVICE_VERSION}
      - MODEL_SERVICE_VERSION=${MODEL_SERVICE_VERSION}
      - PORT=${CONTAINER_PORT}
    restart: always
    volumes:
        - ./appdata:/app/data
    networks:
      - app-network

  model-service:
    image: ${MODEL_SERVICE_IMAGE}:${MODEL_SERVICE_VERSION}
    ports:
      - "${MODEL_SERVICE_PORT}:{CONTAINER_PORT}"
    environment:
      - PORT=${CONTAINER_PORT}
      - HOST=0.0.0.0
    restart: always
    volumes:
        - ./appdata:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge