version: '3.8'

services:
  app:
    image: ghcr.io/remla25-team1/app:latest
    ports:
      - "8080:8080"
    environment:
      - MODEL_SERVICE_URL=http://model-service:8080/predict
    networks:
      - app-network

  model-service:
    image: ghcr.io/remla25-team1/model-service:latest
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge