services:
  app:
    image: ${APP_SERVICE_IMAGE}:${APP_SERVICE_VERSION}
    ports:
      - "${APP_SERVICE_PORT}:${CONTAINER_PORT}"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - CACHE_TTL=${CACHE_TTL}
      - MODEL_SERVICE_HOST=${MODEL_SERVICE_HOST}
      - APP_VERSION=${APP_SERVICE_VERSION}
      - MODEL_SERVICE_PORT=${MODEL_SERVICE_INTERNAL_PORT}
      - PORT=${CONTAINER_PORT}
    restart: always
    volumes:
      - ./secrets/dummy_secret.txt:/run/secrets/dummy_secret:ro
    networks:
      - app-network


  model-service:
    image: ${MODEL_SERVICE_IMAGE}:${MODEL_SERVICE_VERSION}
    ports:
      - "${MODEL_SERVICE_PORT}:${CONTAINER_PORT}"
    environment:
      - PORT=${CONTAINER_PORT}
      - HOST=0.0.0.0
      - MODEL_VERSION=${MODEL_VERSION} 
      - MODEL_DIR=/app/output 
    restart: always
    volumes:
      - ./cached_model:/app/output
    networks:
      - app-network
   

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge