{
 "title": "tweet-sentiment",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "correction_request_counter",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "correction_requests_total", "legendFormat": "__auto" },
    { "downsampler": "mean", "type": "resample", "upsampler": "fillna" }
   ]
  },
  {
   "title": "Histogram of /sentiment response time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(le) (sentiment_response_time_seconds_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "sentiment in progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sentiment_requests_in_progress", "legendFormat": "{{model_version}}" }
   ]
  },
  {
   "title": "sentiment prediction",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sentiment_requests_total", "legendFormat": "{{prediction}}" }
   ]
  }
 ]
}