{{- /*
Generate one DestinationRule per key in .Values.destinationRules.
The key (e.g. "app" or "modelService") is used to build the resource name,
and we pull host/subset data from the map.
*/ -}}
{{- range $key, $dr := .Values.destinationRules }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | lower | trunc 63 }}
spec:
  host: {{ printf "%s-%s" $.Release.Name $dr.host | trunc 63  }}
  subsets:
    {{- range $dr.subsets }}
    - name: {{ .name }}
      labels:
        version: {{ .version }}
    {{- end }}
---
{{- end }}
