apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-{{ .Values.gateway.name }}
spec:
  selector:
{{ .Values.gateway.selector | toYaml | nindent 4 }}

  servers:
{{- range .Values.gateway.servers }}
  - port:
      number: {{ .port.number }}
      name: {{ .port.name }}
      protocol: {{ .port.protocol }}
    hosts:
{{ .hosts | toYaml | nindent 6 }}
{{- end }}

