{
 "title": "sentiment-app",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "le_threshold", "query": "0.1,0.2,0.3,0.5,1.0,2.0\n" }
  ]
 },
 "panels": [
  {
   "title": "AB Test",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app_version) (\n  rate(sentiment_response_time_seconds_sum{app_version=\"0.0.9\"}[$__interval])\n)\n/\nsum by (app_version) (\n  rate(sentiment_response_time_seconds_count{app_version=\"0.0.9\"}[$__interval])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (app_version) (\n  rate(sentiment_response_time_seconds_sum{app_version=\"0.0.10\"}[$__interval])\n)\n/\nsum by (app_version) (\n  rate(sentiment_response_time_seconds_count{app_version=\"0.0.10\"}[$__interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sentiment response time",
   "type": "stat",
   "description": "This panel shows the average response time (in seconds) of the /sentiment endpoint, grouped by app version and source type (model or cache).\n\nThe values are computed as:\n  rate(sum) / rate(count)\nfrom Prometheus histogram metrics, reflecting the smoothed average over time.\n\n- `model` indicates actual model service computation\n- `cache` indicates responses returned from Redis cache\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app_version, source) (\n  rate(sentiment_response_time_seconds_sum[$__interval])\n)\n/\nsum by (app_version, source) (\n  rate(sentiment_response_time_seconds_count[$__interval])\n)",
     "legendFormat": "{{app_version}}, {{source}}"
    }
   ]
  },
  {
   "title": "User Correction Rate",
   "type": "gauge",
   "description": "This panel shows the percentage of sentiment predictions that were corrected by users via the /correction endpoint.\n\n- Green: correction rate < 20% — acceptable\n- Yellow: 20–50% — moderate misclassification, needs attention\n- Red: >50% — high correction rate, model behavior is risky\n\nA high correction rate may suggest accuracy problems or poor generalization in the deployed model.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app_version) (\n  rate(correction_requests_total{}[$__interval])\n  /\n  rate(sentiment_requests_total{}[$__interval])\n)\n\n",
     "legendFormat": "__auto"
    },
    { "expr": "correction_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sentiment requests in progress",
   "type": "gauge",
   "description": "This panel shows the current number of in-progress /sentiment requests for each app version, measured using a Prometheus gauge metric.\n\nSince this is a real-time snapshot, values may often appear as 0 unless requests are active during the scrape interval.\n\nTo capture visible activity, ensure:\n- Sufficient concurrency during requests\n- Prometheus scrape interval is set to 1–2 seconds\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sentiment_requests_in_progress\n\n",
     "legendFormat": "{{app_version}}"
    }
   ]
  },
  {
   "title": "Requests Under Latency Threshold",
   "type": "stat",
   "description": "This panel shows the proportion of requests with response time less than or equal to the selected latency threshold (e.g., 0.3s), calculated from Prometheus histogram buckets. Adjust the `$le_threshold` variable to change the threshold.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app_version) (\n  rate(sentiment_response_time_seconds_bucket{le=\"$le_threshold\"}[$__interval])\n)\n/\nsum by (app_version) (\n  rate(sentiment_response_time_seconds_count[$__interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sentiment request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (app_version) (\n  sentiment_requests_total\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}