apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-application-config
data:
  # App config
  APP_VERSION:       "{{ .Values.config.appVersion }}"
  MODEL_SERVICE_VERSION: "{{ .Values.config.modelServiceVersion }}"
  PORT:              "{{ .Values.config.port }}"

  # Model-service config
  MODEL_SERVICE_HOST: {{ printf "%s-%s" $.Release.Name $.Values.config.modelServiceHost }}
  MODEL_SERVICE_PORT: "{{ .Values.config.modelServicePort }}"
  

  # Redis config
  REDIS_HOST:         "{{ .Release.Name }}-redis"
  REDIS_PORT:         "6379"

  # Listener
  HOST:              "{{ .Values.config.host }}"
