apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-application-config-v1
data:
  # App config
  APP_VERSION:       "{{ .Values.config.appVersionV1 }}"
  MODEL_SERVICE_VERSION: "{{ .Values.config.modelServiceVersion }}"
  PORT:              "{{ .Values.config.port }}"

  # Model-service config
  MODEL_SERVICE_HOST: {{ printf "%s-%s" $.Release.Name $.Values.config.modelServiceHost }}
  MODEL_SERVICE_PORT: "{{ .Values.config.modelServicePort }}"

  # Redis config
  REDIS_HOST:         "{{ .Release.Name }}-redis"
  REDIS_PORT:         "6379"
  
  # Listener
  HOST:              "{{ .Values.config.host }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-application-config-v2
data:
  # App config
  APP_VERSION:       "{{ .Values.config.appVersionV2 }}"
  MODEL_SERVICE_VERSION: "{{ .Values.config.modelServiceVersion }}"
  PORT:              "{{ .Values.config.port }}"

  # Model-service config
  MODEL_SERVICE_HOST: {{ printf "%s-%s" $.Release.Name $.Values.config.modelServiceHost }}
  MODEL_SERVICE_PORT: "{{ .Values.config.modelServicePort }}"
  

  # Redis config
  REDIS_HOST:         "{{ .Release.Name }}-redis"
  REDIS_PORT:         "6379"

  # Listener
  HOST:              "{{ .Values.config.host }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-application-config-model-service
data:
  MODEL_SERVICE_VERSION: "{{ .Values.config.modelServiceVersion }}"
  MODEL_VERSION:       "{{ .Values.config.modelVersion }}"
  PORT:              "{{ .Values.config.port }}"
  HOST:              "{{ .Values.config.host }}"