apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-configmap
data:
{{- range $key, $val := .Values.app.env }}
  {{ $key }}: "{{ $val }}"
{{- end }}
  MODEL_SERVICE_HOST: {{ printf "%s-model-service" .Release.Name | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-model-configmap
data:
{{- range $key, $val := .Values.model.env }}
  {{ $key }}: "{{ $val }}"
{{- end }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-dashboard
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  tweet-sentiment-dashboard.json: |
{{ .Files.Get "dashboards/tweet-sentiment-dashboard.json" | indent 4 }}
