apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-model-service
  labels:
    app: {{ .Release.Name }}-model-service
spec:
  selector:
    app: {{ .Release.Name }}-model-service
  ports:
    - protocol: {{ .Values.modelService.service.protocol }}
      port: {{ .Values.modelService.service.port }}
      targetPort: {{ .Values.modelService.service.targetPort }}
