apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-model-service
spec:
  selector:
    app: {{ .Release.Name }}-model-service
  ports:
    - port: {{ .Values.model.servicePort }}
      targetPort: {{ .Values.model.containerPort }}

