{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-app-monitor
  labels:
    release: {{ .Values.monitoring.release }} 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tweet-sentiment
  endpoints:
    - port: http 
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
