# playbooks/general.yaml
- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        state: present

    - name: Add Kubernetes apt repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
        state: present
        update_cache: yes
        filename: kubernetes

    # step 10
    - name: Install kubelet, kubeadm and kubectl, kubeadm and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    # step 5
    - name: Disable swap
      shell: swapoff -a

    - name: Ensure swap is disabled in fstab
      replace:
        path: /etc/fstab
        regexp: '^(.*swap.*)$'
        replace: '# \1'

    - name: Generate cluster hosts entries
      set_fact:
        cluster_hosts: |
          {{ ctrl_ip }} k8s-ctrl
          {% for i in range(1, worker_count + 1) %}
          {{ cluster_network }}.{{ 100 + i }} k8s-node-{{ i }}
          {% endfor %}

    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: "{{ cluster_hosts }}"
        marker: "# {mark} K8S CLUSTER ENTRIES - ANSIBLE MANAGED"
        insertafter: "^127.0.0.1"
        backup: yes