- hosts: all
  connection: local
  become: yes
  tasks:
    # Registering SSH keys
    - name: Ensure .ssh exists
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: "0700"

    - name: Register all team SSH keys
      ansible.posix.authorized_key:
        user: vagrant
        key: "{{ lookup('file', item) }}"
        state: present
      loop: "{{ lookup('fileglob', '/vagrant/ssh_keys/*.pub', wantlist=True) }}"

    # Disable SWAP
    - name: Disable SWAP
      ansible.builtin.shell: swapoff -a

    - name: Remove the swap entry from the /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: "^(.*swap.*)$"
        line: '# \1'
        backrefs: yes

    # br_netfilter
    - name: Persist kernel modules
      ansible.builtin.copy:
        content: |
          br_netfilter
          overlay
        dest: /etc/modules-load.d/k8s.conf
        mode: "0644"

    - name: Automatically load the kernel modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - br_netfilter
        - overlay

    # Enable IPv4 forwarding
    - name: Enable IP forwarding and bridge settings
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        reload: yes
      loop:
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables

    # Manage /etc/hosts
    - name: Generate cluster hosts entries
      set_fact:
        cluster_hosts: |
          {{ ctrl_ip }} k8s-ctrl
          {% for i in range(1, worker_count + 1) %}
          {{ cluster_network }}.{{ 100 + i }} k8s-node-{{ i }}
          {% endfor %}

    - name: Update /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: "{{ cluster_hosts }}"
        marker: "# {mark} K8S CLUSTER ENTRIES - ANSIBLE MANAGED"
        insertafter: "^127.0.0.1"
        backup: yes