- name: Deploy application manifests, label nodes, enable Istio Traffic Management
  hosts: ctrl
  vars:
    manifests:
      - model-service.yaml
      - app.yaml
      - ingress.yaml
      - application-config.yaml
      - app-v1.yaml
      - app-v2.yaml
      - redis.yaml
      - istio/gateway.yaml
      - istio/destinationrules.yaml
      - istio/virtualservices.yaml
  tasks:
    - name: Copy kubeconfig from controller to vagrant home directory
      ansible.builtin.shell: sudo cat /etc/kubernetes/admin.conf > /home/vagrant/.kube/config
      args:
        creates: /home/vagrant/.kube/config  # skip if already exists

    - name: Fix permissions on kubeconfig
      ansible.builtin.file:
        path: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Create (or refresh) GHCR imagePullSecret
      ansible.builtin.shell: >
        kubectl create secret docker-registry ghcr-secret
        --docker-server=ghcr.io
        --docker-username={{ github_username }}
        --docker-password={{ github_pat }}
        --docker-email={{ github_email }}
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      register: secret_out
      failed_when: secret_out.rc not in [0,1]

    - name: Label default namespace for Istio injection
      shell: kubectl label namespace default istio-injection=enabled --overwrite
      environment:
        KUBECONFIG: /home/vagrant/.kube/config

    - name: Ensure /home/vagrant/istio directory exists on controller
      file:
        path: /home/vagrant/istio
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy Kubernetes manifests to controller
      copy:
        src: "{{ playbook_dir }}/../k8s/{{ item }}"
        dest: "/home/vagrant/{{ item }}"
        mode: "0644"
      loop: "{{ manifests }}"


    - name: Apply Kubernetes manifests
      ansible.builtin.shell: kubectl apply -f {{ item }}
      args:
        chdir: /home/vagrant
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      loop: "{{ manifests }}"

    - name: Label application nodes
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      command: kubectl label node {{ item.name }} node-role={{ item.role }} --overwrite
      loop:
        - { name: "k8s-node-1", role: "model" }
        - { name: "k8s-node-2", role: "app" }

    # Fetch kubeconfig from ctrl node to the Ansible control machine
    - name: Fetch kubeconfig for host machine use
      fetch:
        src: /home/vagrant/.kube/config
        dest: ../kubeconfig-vagrant # this saves the kube-config in the project directory
        flat: yes
      become: true
      become_user: vagrant

    - name: Ensure KUBECONFIG export is in local shell session
      delegate_to: localhost
      run_once: true
      ansible.builtin.shell: export KUBECONFIG={{ playbook_dir }}/../kubeconfig-vagrant

    - name: Wait for pods to be ready
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      command: kubectl wait --for=condition=Ready pods --all --timeout=120s

    - name: Display node labels
      ansible.builtin.command: kubectl get nodes --show-labels
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      register: nodes_out

    - name: Print node label output
      ansible.builtin.debug:
        var: nodes_out.stdout_lines

    - name: Display pod placement
      ansible.builtin.command: kubectl get pods -o wide
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      register: pods_out

    - name: Print pod distribution
      ansible.builtin.debug:
        var: pods_out.stdout_lines

    - name: Get Gateway details
      shell: kubectl get gateway app-gateway
      environment:
        KUBECONFIG: /home/vagrant/.kube/config

    - name: Get DestinationRules details
      shell: kubectl get destinationrule -o wide
      environment:
        KUBECONFIG: /home/vagrant/.kube/config

    - name: Get VirtualServices details
      shell: kubectl get virtualservice -o wide
      environment:
        KUBECONFIG: /home/vagrant/.kube/config

    - name: Get pods with labels
      shell: kubectl get pods --show-labels
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
  
    - name: Output KUBECONFIG export command
      delegate_to: localhost
      run_once: true
      ansible.builtin.debug:
        msg: "Run this in your terminal to be able to use kubectl commands: export KUBECONFIG=$(pwd)/kubeconfig-vagrant"

